name: build_runner_hang_repro
description: A reduced test case of build_runner test hanging issue
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dev_dependencies:
  build_runner: ^2.2.0
  build_test: ^2.1.6
  build_web_compilers: '>=3.2.6 <5.0.0'
  test: ^1.21.0
